[package]
name = "openapi-codegen-native"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"
strip = "symbols"

[profile.dev]
opt-level = 2

[dependencies]
napi = { version = "3", default-features = false, features = ["napi8", "serde-json"] }
napi-derive = "3"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
serde_yaml = "0.9"
regex = "1"
indexmap = { version = "2", features = ["serde"] }
mimalloc = { version = "0.1", default-features = false }
rustc-hash = "2"

[build-dependencies]
napi-build = "2"
